backend:
  name: git-gateway
  branch: main
  site_domain: oceanviewvillamorocco.com # الدومين الجديد

site_url: https://oceanviewvillamorocco.com
display_url: https://oceanviewvillamorocco.com

media_folder: "blog/img"
public_folder: "/blog/img"

collections:
  - name: "blog"
    label: "المقالات"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "عنوان المقال", name: "title", widget: "string"}
      - {label: "الوصف المصغر (SEO)", name: "description", widget: "string"} # مهم لجوجل
      - {label: "الصورة الرئيسية", name: "image", widget: "image"}
      - {label: "رابط فيديو أو Affiliate", name: "external_link", widget: "string", required: false}
      
      - {label: "المقال بالعربية 🇲🇦", name: "body", widget: "markdown"} # الخانة الأساسية
      - {label: "المقال بالإنجليزية 🇬🇧", name: "body_en", widget: "markdown"}
      - {label: "المقال بالفرنسية 🇫🇷", name: "body_fr", widget: "markdown"}
      - {label: "المقال بالهولندية 🇳🇱", name: "body_nl", widget: "markdown"}
      - {label: "المقال بالألمانية 🇩🇪", name: "body_de", widget: "markdown"}
      - {label: "المقال بالإسبانية 🇪🇸", name: "body_es", widget: "markdown"}
